version: '2.2'
services:
  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: esnode1
    environment:
      - node.name=esnode1
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_network
  esnode2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: esnode2
    environment:
      - node.name=esnode2
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode2_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network
volumes:
  esnode1_data:
    driver: local
  esnode2_data:
    driver: local
networks:
  elastic_network:
    driver: bridge